<!-- Begin Footer -->
<br /><br />
<div align="center">
<div align="center" style="border:dashed 1px #999; width:80%;">
	<p style="font-size:xx-small">Copyright &copy; 2012-2013 by:
	Alex Edison, Nicole Erkis, Ruben Martinez, and Allen Tucker.<br />
	<i>Homecheck</i> is free software and comes with absolutely no warranty.  You can redistribute and/or modify it under the terms of the
	     <a href="http://www.gnu.org/copyleft/gpl.html" style="font-weight:normal;"> GNU General Public License</a> as published by the <a href="http://www.fsf.org/"  style="font-weight:normal;"> Free Software Foundation</a>.
	</p>
</div>
</div>
<!-- End Footer -->